- name: Demo
  hosts: all
  tasks:
    - name: Print Helo
      ansible.builtin.debug:
        msg: Hello Universe

# ansible-playbook -i inv -e ansible_user=centos -e ansible_password=DevOps321 01-sample.yml

#comma separated hosts instead of inventory file
# ansible-playbook -i localhost, -e ansible_user=centos -e ansible_password=DevOps321 01-sample.yml