- name: Demo on loops
  hosts: all
  tasks:
    - name: Print Fruit Name
      debug:
        msg: Fruit name is {{ item }}
      loop:
        - apple
        - banana
    - name: Print Fruit Name & Quantity
      debug:
        msg: Fruit name is {{ item.name }}, & Quantity is {{ item.quantity }}
      loop:
        - { name: "apple", quantity: 100 }
        - { name: "banan", quantity: 200 }


# ansible-playbook -i localhost, -e ansible_user=centos -e ansible_password=DevOps321 04-loops.yml

# If connection: local added to play then
# ansible-playbook -i localhost, 04-loops.yml

# OR Use --connection=local in command
# ansible-playbook -i localhost, 04-loops.yml --connection=local
